#DB
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 1234

# JPA configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#Server
server:
  port: 8090
  
#Security
security:
  oauth2:
  resourceserver:
  jwt:
  issuer-uri: ${ISSUER_URI}
  client:
  registration:
  keycloak:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

# JWT Secret
jwt:
  secret: a_very_long_and_secure_secret_key_that_is_at_least_32_bytes_long
# S3 설정
aws:
  s3:
    bucket-name: masils
    