#DB
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://masil.c54ikwwu6859.ap-northeast-2.rds.amazonaws.com:3306/masil?useSSL=false&allowPublicKeyRetrieval=true
    username: masil
    password: masil123

# JPA configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#Server
server:
  port: 8090
  
#Security
security:
  oauth2:
  resourceserver:
  jwt:
  issuer-uri: ${ISSUER_URI}
  client:
  registration:
  keycloak:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

# JWT Secret
jwt:
  secret: a_very_long_and_secure_secret_key_that_is_at_least_32_bytes_long
# S3 설정
aws:
  s3:
    bucket-name: masils
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}